<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('images')->insert([
                [
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_80th001ark_5b0415db1d993_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_80th001ark_5b0415db1d993_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_80th001ark_5b0415db1d993_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_80th001ark_5b0415db1d993_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_80th001ark_5b0415db1d993_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_81b0008wra_5b0554e79789a_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_81b0008wra_5b0554e79789a_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_81b0008wra_5b0554e79789a_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_81b0008wra_5b0554e79789a_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_lenovo_81b0008wra_5b0554e79789a_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'apple_mr962_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'apple_mr962_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'apple_mr962_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_n705ud_gc094_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_n705ud_gc094_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_n705ud_gc094_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_n705ud_gc094_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_n705ud_gc094_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_asus_fx504gd_dm057_5b4f306b5f0cf_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_asus_fx504gd_dm057_5b4f306b5f0cf_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_asus_fx504gd_dm057_5b4f306b5f0cf_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_asus_fx504gd_dm057_5b4f306b5f0cf_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_asus_fx504gd_dm057_5b4f306b5f0cf_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lenovo_legion_y530_15ich_81fv00lyra_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lenovo_legion_y530_15ich_81fv00lyra_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lenovo_legion_y530_15ich_81fv00lyra_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lenovo_legion_y530_15ich_81fv00lyra_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lenovo_legion_y530_15ich_81fv00lyra_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_24mp68vq_p_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_24mp68vq_p_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_24mp68vq_p_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_24mp68vq_p_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_24mp68vq_p_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_25um58_p_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_25um58_p_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_25um58_p_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_25um58_p_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'lg_25um58_p_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'acer_um_wv0ee_006_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'acer_um_wv0ee_006_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'acer_um_wv0ee_006_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'acer_um_wv0ee_006_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'acer_um_wv0ee_006_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_z500kl_1a014a_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_z500kl_1a014a_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_z500kl_1a014a_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_z500kl_1a014a_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'asus_z500kl_1a014a_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '11',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'huawei_mediapad_t3_10_lte_gold_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '11',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'huawei_mediapad_t3_10_lte_gold_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '11',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'huawei_mediapad_t3_10_lte_gold_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '11',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'huawei_mediapad_t3_10_lte_gold_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '11',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'huawei_mediapad_t3_10_lte_gold_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '12',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_pixus_vision_10_1_3g_5a749c016e4e2_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '12',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_pixus_vision_10_1_3g_5a749c016e4e2_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '12',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_pixus_vision_10_1_3g_5a749c016e4e2_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '12',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_pixus_vision_10_1_3g_5a749c016e4e2_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '12',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'copy_pixus_vision_10_1_3g_5a749c016e4e2_images_5.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '13',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'pocketbook_840_pb740_x_cis_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '13',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'pocketbook_840_pb740_x_cis_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '13',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'pocketbook_840_pb740_x_cis_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '13',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'pocketbook_840_pb740_x_cis_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '14',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_one_14506_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '14',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_one_14506_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '14',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_one_14506_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '14',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_one_14506_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '15',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_cambridge_images_1.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '15',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_cambridge_images_2.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '15',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_cambridge_images_3.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '15',
                    'imageable_type' => 'App\Shop\Products\Product',
                    'src' => 'evromedia_cambridge_images_4.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Shop\Categories\Category',
                    'src' => 'laptops.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Shop\Categories\Category',
                    'src' => 'gamer-laptops.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Shop\Categories\Category',
                    'src' => 'work-laptops.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Shop\Categories\Category',
                    'src' => 'monitors.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Shop\Categories\Category',
                    'src' => 'tablets.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Shop\Categories\Category',
                    'src' => 'ebook-readers.jpg',
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ]
            ]
        );
    }
}
