<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'category_id' => '2',
                'name' => 'Lenovo V110 (80TG00AJRK) Black',
                'slug' => 'lenovo-80tg00ajrk',
                'description' => 'Экран 15.6" (1366x768) WXGA HD, матовый / Intel Pentium N4200 (1.1 - 2.5 ГГц) / RAM 4 ГБ / SSD 128 ГБ / Intel HD Graphics 505 / DVD Super Multi / LAN / Wi-Fi / Bluetooth / веб-камера / DOS / 1.9 кг / черный',
                'price' => '389.9',
                'status' => '1',
                'quantity' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '2',
                'name' => 'Apple MacBook Pro 15" Silver (MR962) lg 2 2018',
                'slug' => 'apple-mr962',
                'description' => 'Экран 15.4" IPS (2880x1800), глянцевый / Intel Core i7-8750H (2.2 - 4.1 ГГц) / RAM 16 ГБ / SSD 256 ГБ / AMD Radeon Pro 555X, 4 ГБ / Wi-Fi / Bluetooth / веб-камера / Mac OS High Sierra / 1.83 кг / серебристый',
                'price' => '2238.2',
                'status' => '1',
                'quantity' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '2',
                'name' => 'Lenovo lg 2 IdeaPad V330-14IKB (81B000DDUA) Iron Grey',
                'slug' => 'lenovo-81b000ddua',
                'description' => 'Экран 14" (1920x1080) Full HD, глянцевый с антибликовым покрытием / Intel Core i3-8130U (2.2 - 3.4 ГГц) / RAM 8 ГБ / SSD 128 ГБ / Intel UHD 620 / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / DOS / 1.75 кг / серый',
                'price' => '504.0',
                'status' => '1',
                'quantity' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '3',
                'name' => 'ASUS VivoBook Pro 17 N705UD-GC094 (90NB0GA1-M01300) Dark Grey',
                'slug' => 'asus-n705ud-gc094',
                'description' => 'Экран 17.3" (1920x1080) Full HD, матовый / Intel Core i5-8250U (1.6 - 3.4 ГГц) / RAM 12 ГБ / HDD 1 ТБ + SSD 128 ГБ / nVidia GeForce GTX 1050, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / Без ОС / 2.2 кг / серый металик',
                'price' => '1199.9',
                'status' => '1',
                'quantity' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '3',
                'name' => 'ASUS lg 2 TUF Gaming FX504GE-DM048 (90NR00I1-M00490) Black',
                'slug' => 'asus-fx504ge-dm048',
                'description' => 'Экран 15.6" (1920x1080) Full HD, матовый / Intel Core i5-8300H (2.3 - 4.0 ГГц) / RAM 8 ГБ / SSHD 1 ТБ + 8 ГБ / nVidia GeForce GTX 1050 Ti, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / Endless OS / 2.3 кг / черный',
                'price' => '859.9',
                'status' => '1',
                'quantity' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '3',
                'name' => 'Lenovo Legion Y530-15ICH (81FV00LYRA) Black lg 2',
                'slug' => 'lenovo-legion-y530-15ich-81fv00lyra',
                'description' => 'Экран 15.6" IPS (1920x1080) Full HD, матовый / Intel Core i5-8300H (2.3 - 4.0 ГГц) / RAM 16 ГБ / HDD 1 ТБ / nVidia GeForce GTX 1050Ti, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / DOS / 2.3 кг / черный',
                'price' => '1118.2',
                'status' => '1',
                'quantity' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '4',
                'name' => 'LG 24MP68VQ-P 24"',
                'slug' => 'lg-24mp68vq-p',
                'description' => 'Тип матрицы: IPS / Время реакции матрицы: 5 мс / Яркость дисплея: 250 кд/м² / Контрастность дисплея: 1000:1 / Особенности: "Безрамочный" (Сinema screen)',
                'price' => '229.9',
                'status' => '1',
                'quantity' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '4',
                'name' => 'LG 25UM58-P 25"',
                'slug' => 'lg-25um58-p-bl',
                'description' => 'Тип матрицы: IPS / Время реакции матрицы: 5 мс (GtG) / Яркость дисплея: 250 кд/м² / Контрастность дисплея: 1000:1 / Особенности: Flicker-Free',
                'price' => '219.9',
                'status' => '1',
                'quantity' => '14',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '4',
                'name' => 'Acer Nitro VG220Qbmiix (UM.WV0EE.006) 21.5"',
                'slug' => 'acer-um-wv0ee-006',
                'description' => 'Тип матрицы: IPS / Время реакции матрицы: 1 мс / Яркость дисплея: 250 кд/м² / Контрастность дисплея: Статическая: 1000:1 / Динамическая: 100M:1 / Особенности: LED-подсветка ,  Flicker-Free',
                'price' => '299.9',
                'status' => '1',
                'quantity' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '5',
                'name' => 'Asus ZenPad 3S 10 32GB Slate Gray (Z500KL-1A014A)',
                'slug' => 'asus-z500kl-1a014a-gr',
                'description' => 'Экран 9.7" IPS (2048x1536) емкостный MultiTouch / Qualcomm MSM8956 (1.8 ГГц) / RAM 4 ГБ / 32 ГБ встроенной памяти + microSD / 3G / Wi-Fi 802.11 a/b/g/n/ac / Bluetooth 4.1 / основная камера 8 Мп, фронтальная - 5 Мп / GPS / ГЛОНАСС / ОС Android 6.0 (Marshmallow) / 490 г / серый',
                'price' => '459.9',
                'status' => '1',
                'quantity' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '5',
                'name' => 'Pixus Vision 10.1 3G 3/16GB',
                'slug' => 'pixus-vision-10_1-3g-3-16g',
                'description' => 'Экран 10.1" IPS (1920x1200) MultiTouch / MediaTek MT6753 (1.3 ГГц) / RAM 3 ГБ / 16 ГБ встроенной памяти + microSD / 3G / LTE / Wi-Fi / Bluetooth 4.0 / основная камера 5 Мп, фронтальная - 2 Мп / GPS / A-GPS / поддержка 2-х СИМ-карт / Android 7.0 (Nougat) / 450 г / черный',
                'price' => '177.7',
                'status' => '1',
                'quantity' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '5',
                'name' => 'Huawei MediaPad T3 10 LTE Gold (AGS-L09)',
                'slug' => 'huawei-mediapad-t3-10-lte',
                'description' => 'Экран 9.6" IPS (1280x800) MultiTouch / Qualcomm Snapdragon 425 (1.4 ГГц) / RAM 2 ГБ / 16 ГБ встроенной памяти + microSD / 3G / LTE / Wi-Fi / Bluetooth / основная камера 5 Мп, фронтальная 2 Мп / GPS / Android 7.0 (Nougat) / 460 г / золотистый',
                'price' => '249.9',
                'status' => '1',
                'quantity' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '6',
                'name' => 'PocketBook InkPad 3 740 Dark Brown (PB740-X-CIS) lg 2',
                'slug' => 'pocketbook-pb740-x-cis-roz',
                'description' => 'Количество градаций серого: 16 / Диагональ дисплея: 8" / Разрешение: 1872x1404 / Тип матрицы: E Ink Carta / Встроенная память: 8 ГБ / Вес: 210 г',
                'price' => '219.9',
                'status' => '1',
                'quantity' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '6',
                'name' => 'Evromedia lg 2 E-Учебник One',
                'slug' => 'evromedia-one-14506',
                'description' => 'Количество градаций серого: 16 / Диагональ дисплея: 6" / Разрешение: 800х600 / Тип матрицы: E Ink / Встроенная память: 8 ГБ / Вес: 180 г',
                'price' => '74.9',
                'status' => '1',
                'quantity' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id' => '6',
                'name' => 'EvroMedia Cambridge (14 538)',
                'slug' => 'evromedia-cambridge',
                'description' => 'Количество градаций серого: 16 / Диагональ дисплея: 6" / Разрешение: 800х600 / Тип матрицы: E Ink / Встроенная память: 8 ГБ / Вес: 180 г',
                'price' => '97.9',
                'status' => '1',
                'quantity' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]
        ]);
    }
}
